apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: orchestrator-backend-config
  namespace: ai-agents
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: "HTTP"
    requestPath: "/healthz"
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 86400

---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: proxy-agent-backend-config
  namespace: ai-agents
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: "HTTP"
    requestPath: "/healthz"
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 86400