apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-system-ingress
  namespace: ai-agents
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashboard-service
            port:
              number: 80
      - path: /conversation
        pathType: Prefix
        backend:
          service:
            name: proxy-agent-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: orchestrator-service
            port:
              number: 80