apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-agent
  namespace: ai-agents
  labels:
    app: proxy-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-agent
  template:
    metadata:
      labels:
        app: proxy-agent
    spec:
      serviceAccountName: ai-agent-ksa
      containers:
        - name: proxy-agent-container
          image: asia-east1-docker.pkg.dev/gke-10-hackathon-471902/ai-agents-repo/ai-agent-base:latest
          imagePullPolicy: Always
          command: ["uvicorn", "app.workers.proxy:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: GCP_PROJECT_ID
              value: "gke-10-hackathon-471902"
            - name: GCP_FIRESTORE_NAME
              value: "gke-10-hackathon"
            - name: PROXY_AGENT_SUBSCRIPTION_ID
              value: "proxy-agent-sub"
            - name: AGENT_REGISTRY_SUBSCRIPTION_ID
              value: "rag-index"
            - name: PYTHONPATH
              value: "/code"
            - name: RAG_KB_ID
              valueFrom:
                configMapKeyRef:
                  name: rag-config
                  key: RAG_KB_ID
            - name: RAG_ENDPOINT_NAME
              valueFrom:
                configMapKeyRef:
                  name: rag-config
                  key: RAG_ENDPOINT_NAME
            - name: RAG_DEPLOYED_INDEX_ID
              valueFrom:
                configMapKeyRef:
                  name: rag-config
                  key: RAG_DEPLOYED_INDEX_ID
          workingDir: /code

---

apiVersion: v1
kind: Service
metadata:
  name: proxy-agent-service
  namespace: ai-agents
  annotations:
    cloud.google.com/backend-config: '{"default": "proxy-agent-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: proxy-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
